import { toHex, toRgb } from "@/lib/color/color";
import { siteConfig } from "@/lib/site";
import type { Oklch } from "@/types/color";
import type { DesignTokens } from "@/types/tokens";

/**
 * Generators for native and design-tool formats: Flutter, SwiftUI and Tokens Studio for Figma.
 * Like the web formats they read only `DesignTokens`, so every export describes the same system.
 */

const headerText = (tokens: DesignTokens) =>
  `${tokens.meta.name} - design tokens generated by DesignHub (${siteConfig.github})`;

/** "Acme Labs" -> "AcmeLabs"; falls back to "Brand" for names without letters. */
function pascal(name: string): string {
  const words = name.match(/[A-Za-z0-9]+/g) ?? [];
  const joined = words.map((word) => word[0]!.toUpperCase() + word.slice(1)).join("");
  return /^[A-Za-z]/.test(joined) ? joined : `Brand${joined}`;
}

/** "indigo-500" -> "indigo500", "0.5" -> "s0_5"; identifiers can't start with a digit. */
function ident(name: string, digitPrefix: string): string {
  const parts = name
    .replace(/\./g, "_")
    .split(/[^A-Za-z0-9_]+/)
    .filter(Boolean);
  const camel = parts.map((part, i) => (i === 0 ? part : part[0]!.toUpperCase() + part.slice(1))).join("");
  return /^[0-9]/.test(camel) ? `${digitPrefix}${camel}` : camel;
}

/** Collects unique identifiers in order, dropping later duplicates. */
function unique<T extends { id: string }>(items: T[]): T[] {
  const seen = new Set<string>();
  return items.filter((item) => (seen.has(item.id) ? false : (seen.add(item.id), true)));
}

type ColorEntry = { id: string; value: Oklch; comment?: string };

function colorEntries(tokens: DesignTokens, digitPrefix: string): ColorEntry[] {
  const list: ColorEntry[] = [];
  tokens.colors.forEach((color) => {
    list.push({ id: ident(color.name, digitPrefix), value: color.value });
    // The underscore keeps "indigo-2" shade 50 (indigo2_50) apart from "indigo" shade 250 (indigo_250).
    color.shades.forEach((shade) =>
      list.push({ id: ident(`${color.name}_${shade.step}`, digitPrefix), value: shade.value }),
    );
  });
  tokens.semantic.forEach((role) =>
    list.push({ id: ident(role.name, digitPrefix), value: role.value, comment: `semantic, ${role.ref}` }),
  );
  return unique(list);
}

const px = (value: number) => (value >= 9999 ? 9999 : Math.round(value * 100) / 100);
const weight = (value: number) => Math.min(900, Math.max(100, Math.round(value / 100) * 100));

/* ------------------------------------------------------------------ Flutter */

/** Material text theme slots for each step of the type scale, smallest to largest. */
const flutterSlots: Record<string, string> = {
  xs: "labelSmall",
  sm: "bodySmall",
  base: "bodyMedium",
  lg: "bodyLarge",
  xl: "titleLarge",
  "2xl": "headlineSmall",
  "3xl": "headlineMedium",
  "4xl": "headlineLarge",
  "5xl": "displaySmall",
  "6xl": "displayMedium",
};

const dartString = (value: string) => `'${value.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;

function dartColor(value: Oklch): string {
  const { r, g, b, alpha } = toRgb(value);
  const hex = [Math.round(alpha * 255), r, g, b].map((channel) => channel.toString(16).padStart(2, "0")).join("");
  return `Color(0x${hex.toUpperCase()})`;
}

/** Flutter: color, spacing, radius and font constants plus a Material 3 `ThemeData`. */
export function toFlutterTheme(tokens: DesignTokens): string {
  const name = pascal(tokens.meta.name);
  const lower = name[0]!.toLowerCase() + name.slice(1);
  const colors = colorEntries(tokens, "c");
  const primary = tokens.semantic.find((role) => role.name === "primary")?.value ?? tokens.colors[0]?.value;
  const t = tokens.typography;

  const colorLines = colors
    .map(
      (color) =>
        `  static const ${color.id} = ${dartColor(color.value)};${color.comment ? ` // ${color.comment}` : ""}`,
    )
    .join("\n");
  const doubles = (items: { name: string; px: number }[]) =>
    unique(items.map((item) => ({ id: ident(item.name, "s"), px: item.px })))
      .map((item) => `  static const double ${item.id} = ${px(item.px)};`)
      .join("\n");
  const textStyles = t
    ? t.steps
        .filter((step) => flutterSlots[step.name])
        .map((step) => {
          const heading = step.maxPx >= 24;
          const family = heading ? `${name}Fonts.heading` : `${name}Fonts.body`;
          const w = weight(heading ? t.rhythm.headingWeight : t.rhythm.bodyWeight);
          const height = heading ? t.rhythm.headingLineHeight : t.rhythm.bodyLineHeight;
          return `    ${flutterSlots[step.name]}: TextStyle(fontFamily: ${family}, fontSize: ${px(step.maxPx)}, fontWeight: FontWeight.w${w}, height: ${height}),`;
        })
        .join("\n")
    : "";

  return `// ${headerText(tokens)}
// Add the fonts to pubspec.yaml (or use the google_fonts package) for the families below to load.
import 'package:flutter/material.dart';

class ${name}Colors {
  ${name}Colors._();
${colorLines}
}

class ${name}Spacing {
  ${name}Spacing._();
${doubles(tokens.spacing)}
}

class ${name}Radius {
  ${name}Radius._();
${doubles(tokens.radius)}
}
${
  t
    ? `
class ${name}Fonts {
  ${name}Fonts._();
  static const heading = ${dartString(t.heading.family)};
  static const body = ${dartString(t.body.family)};
}
`
    : ""
}
ThemeData ${lower}Theme({Brightness brightness = Brightness.light}) {
  return ThemeData(
    useMaterial3: true,
    colorScheme: ColorScheme.fromSeed(seedColor: ${primary ? dartColor(primary) : "Colors.indigo"}, brightness: brightness),${t ? `\n    fontFamily: ${name}Fonts.body,` : ""}
    cardTheme: CardThemeData(shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(${px(tokens.radius.find((r) => r.name === "lg")?.px ?? 12)}))),${
      textStyles ? `\n    textTheme: const TextTheme(\n${textStyles}\n    ),` : ""
    }
  );
}
`;
}

/* ------------------------------------------------------------------ SwiftUI */

const round3 = (value: number) => Math.round(value * 1000) / 1000;
const swiftString = (value: string) => `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

function swiftColor(value: Oklch): string {
  const { r, g, b, alpha } = toRgb(value);
  const channels = `red: ${round3(r / 255)}, green: ${round3(g / 255)}, blue: ${round3(b / 255)}`;
  return `Color(${channels}${alpha < 1 ? `, opacity: ${round3(alpha)}` : ""})`;
}

/**
 * SwiftUI: colors as `Color` extensions (prefixed with the brand, so they never clash with
 * system colors such as `Color.indigo`), plus spacing, radius and font helpers.
 */
export function toSwiftUITheme(tokens: DesignTokens): string {
  const name = pascal(tokens.meta.name);
  const prefix = name[0]!.toLowerCase() + name.slice(1);
  const colors = colorEntries(tokens, "c").map((color) => ({
    ...color,
    id: `${prefix}${color.id[0]!.toUpperCase()}${color.id.slice(1)}`,
  }));
  const t = tokens.typography;
  const lets = (items: { name: string; px: number }[]) =>
    unique(items.map((item) => ({ id: ident(item.name, "s"), px: item.px })))
      .map((item) => `    static let ${item.id}: CGFloat = ${px(item.px)}`)
      .join("\n");

  const fonts = t
    ? `
enum ${name}Font {
    static let headingFamily = ${swiftString(t.heading.family)}
    static let bodyFamily = ${swiftString(t.body.family)}

    /// Font files must be added to the app target and listed under UIAppFonts in Info.plist.
    static func heading(_ size: CGFloat) -> Font { .custom(headingFamily, size: size).weight(.${swiftWeight(t.rhythm.headingWeight)}) }
    static func body(_ size: CGFloat) -> Font { .custom(bodyFamily, size: size) }

${unique(t.steps.map((step) => ({ id: ident(step.name, "size"), step })))
  .map(({ id, step }) => `    static let ${id} = ${step.maxPx >= 24 ? "heading" : "body"}(${px(step.maxPx)})`)
  .join("\n")}
}
`
    : "";

  return `// ${headerText(tokens)}
import SwiftUI

extension Color {
${colors.map((color) => `    static let ${color.id} = ${swiftColor(color.value)}${color.comment ? ` // ${color.comment}` : ""}`).join("\n")}
}

enum ${name}Spacing {
${lets(tokens.spacing)}
}

enum ${name}Radius {
${lets(tokens.radius)}
}
${fonts}`;
}

function swiftWeight(value: number): string {
  const names: Record<number, string> = {
    100: "ultraLight",
    200: "thin",
    300: "light",
    400: "regular",
    500: "medium",
    600: "semibold",
    700: "bold",
    800: "heavy",
    900: "black",
  };
  return names[weight(value)] ?? "regular";
}

/* ------------------------------------------------------------ Tokens Studio */

type StudioToken = { value: string | Record<string, string>; type: string; description?: string };
type StudioGroup = { [key: string]: StudioToken | StudioGroup };

const percent = (value: number) => `${Math.round(value * 1000) / 10}%`;

/**
 * Tokens Studio for Figma: one "global" set with colors, semantic aliases, spacing, radii and
 * typography, in the plugin's JSON format (load it with Tools, Load from file).
 */
export function toTokensStudio(tokens: DesignTokens): string {
  const color: StudioGroup = {};
  tokens.colors.forEach((token) => {
    const group: StudioGroup = { base: { value: toHex(token.value), type: "color" } };
    token.shades.forEach((shade) => (group[String(shade.step)] = { value: toHex(shade.value), type: "color" }));
    color[token.name] = group;
  });
  const semantic: StudioGroup = {};
  tokens.semantic.forEach((role) => {
    const inPalette = tokens.colors.some((token) => token.name === role.ref);
    semantic[role.name] = { value: inPalette ? `{color.${role.ref}.base}` : toHex(role.value), type: "color" };
  });
  const dimension = (items: { name: string; px: number }[], type: string): StudioGroup =>
    Object.fromEntries(items.map((item) => [item.name.replace(/\./g, "_"), { value: String(px(item.px)), type }]));

  const global: StudioGroup = {
    color,
    semantic,
    spacing: dimension(tokens.spacing, "spacing"),
    borderRadius: dimension(tokens.radius, "borderRadius"),
  };

  const t = tokens.typography;
  if (t) {
    global.fontFamilies = {
      heading: { value: t.heading.family, type: "fontFamilies" },
      body: { value: t.body.family, type: "fontFamilies" },
    };
    global.fontWeights = {
      heading: { value: String(t.rhythm.headingWeight), type: "fontWeights" },
      body: { value: String(t.rhythm.bodyWeight), type: "fontWeights" },
    };
    global.lineHeights = {
      heading: { value: percent(t.rhythm.headingLineHeight), type: "lineHeights" },
      body: { value: percent(t.rhythm.bodyLineHeight), type: "lineHeights" },
    };
    global.letterSpacing = {
      heading: { value: percent(t.rhythm.headingTracking), type: "letterSpacing" },
      body: { value: percent(t.rhythm.bodyTracking), type: "letterSpacing" },
    };
    global.fontSizes = Object.fromEntries(
      t.steps.map((step) => [step.name, { value: String(px(step.maxPx)), type: "fontSizes" }]),
    );
    global.typography = Object.fromEntries(
      t.steps.map((step) => {
        const role = step.maxPx >= 24 ? "heading" : "body";
        return [
          step.name,
          {
            value: {
              fontFamily: `{fontFamilies.${role}}`,
              fontWeight: `{fontWeights.${role}}`,
              lineHeight: `{lineHeights.${role}}`,
              letterSpacing: `{letterSpacing.${role}}`,
              fontSize: `{fontSizes.${step.name}}`,
            },
            type: "typography",
          },
        ];
      }),
    );
  }

  const document = {
    global,
    $themes: [],
    $metadata: { tokenSetOrder: ["global"] },
  };
  return `${JSON.stringify(document, null, 2)}\n`;
}
